### ISSUE TITLE
MQTT lightningdetector/detect not updating count and distance

### ISSUE THREAD

**Issue by lightmaster** [ironsheep/lightning-detector-MQTT2HA-Daemon#8]
**Checklist:**

- [x] I updated to the latest version available
- [x] I double-checked my hardware connections
- [x] I checked that my MQTT broker is otherwise working

**Release with the issue:**
v2.0.3
**Last working release (if known):**

**Hardware, Operating System, Python version:**
RPi 3B, Raspberry Pi OS, Python 3.7.3

**Description of problem:**
MQTT messages to `detect` for `count` and `distance` always equal 1, even though the messages sent to `crings` and `prings` count properly and show reasonable distances.

![MQTT Lightning Detect Count bug](https://user-images.githubusercontent.com/5307827/91115398-1f9b3f80-e658-11ea-899a-29af164d21a6.png)

**Python errors shown in the logs (if applicable):**

```

```

**Additional information:**

**Comment by ironsheep** [comment]
A review of code shows nothing notable.  I'm going to have to recreate this to find the problem.  More soonish....

**Comment by ironsheep** [comment]
@lightmaster I'm guessing that our latest finding is the explanation for this lack of reporting?  I'll bet when you proved the AS3935 is communicating this will be better!

**Comment by ironsheep** [comment]
Is this fixed too then?

**Comment by lightmaster** [comment]
I need some lightning to know that, lol. Where's Thor when you need him?

**Comment by ironsheep** [comment]
I'll leave this open so you can post status when you finally hear some...  ;-)

**Comment by lightmaster** [comment]
Nope, MQTT is still showing 1 count on the Home Assistant MQTT Integrations card.

![Lovelace Card showing 2 strikes](https://i.postimg.cc/fbqpQWkg/Lovelace-Card-showing-2-strikes.png)

![MQTT Devices card showing 1 strike](https://i.postimg.cc/MTc46kQZ/MQTT-Devices-card-showing-1-strike.png)

**Comment by ironsheep** [comment]
I'm not seeing anything wrong here.  

The count should be the count of detections in the last 3 seconds (it only reports every three seconds so we don't storm the MQTT broker.)  If detections are 3 seconds apart, or more, this will be 1.

re: my alternative to your pull request (*Thank you for it and for noting that I should fix this stuff, as always!*)
Changes committed to /master and appear in [v2.2.7](https://github.com/ironsheep/lightning-detector-MQTT2HA-Daemon/releases/tag/v2.2.7) and later.

**Comment by ironsheep** [comment]
Saw your "works great" on my commit.  Good to hear. Closing this issue then.

**Comment by lightmaster** [comment]
I was in the middle of typing up something about it on here and gonna close the issue when I got called away at work.

**Comment by ironsheep** [comment]
No worries, you can always enter more after closing. But I re-opened it for you.
